[build-system]
# Minimum requirements for the build system to execute.

requires = [
    "numpy==1.18.2",
    "scikit-learn==0.23.1",
    "matplotlib==3.2.2",
    "pandas==1.2.4",
    "jax==0.2.13",
    "jaxlib==0.1.67",
    "scipy==1.5.2",
    "PyLaTeX==1.3.2"
]