name: ITEA Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.10", "3.11"]
        os: [ubuntu-latest] # windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install module
        run: | 
          pip install .
      - name: Build and install PyPI dist
        run: |
          rm -f ./dist/*
          python setup.py develop
          python setup.py sdist
          python -m pip install ./dist/*.tar.gz
      - name: Test with pytest
        run: |
          python -m pytest tests/*.py